/** World Bank 국가명(영문) → 한국어 표기 */
export const COUNTRY_NAMES_KO: Record<string, string> = {
  "United States": "미국",
  "Germany": "독일",
  "United Kingdom": "영국",
  "France": "프랑스",
  "Canada": "캐나다",
  "Australia": "호주",
  "Japan": "일본",
  "Korea, Rep.": "대한민국",
  "China": "중국",
  "India": "인도",
  "Russian Federation": "러시아",
  "Brazil": "브라질",
  "Mexico": "멕시코",
  "Spain": "스페인",
  "Italy": "이탈리아",
  "Turkiye": "튀르키예",
  "Turkey": "튀르키예",
  "Saudi Arabia": "사우디아라비아",
  "United Arab Emirates": "아랍에미리트",
  "Singapore": "싱가포르",
  "Malaysia": "말레이시아",
  "Thailand": "태국",
  "Viet Nam": "베트남",
  "Vietnam": "베트남",
  "Philippines": "필리핀",
  "Indonesia": "인도네시아",
  "Pakistan": "파키스탄",
  "Bangladesh": "방글라데시",
  "Nepal": "네팔",
  "Uzbekistan": "우즈베키스탄",
  "Kazakhstan": "카자흐스탄",
  "Ukraine": "우크라이나",
  "Poland": "폴란드",
  "Netherlands": "네덜란드",
  "Belgium": "벨기에",
  "Switzerland": "스위스",
  "Sweden": "스웨덴",
  "Norway": "노르웨이",
  "Denmark": "덴마크",
  "Finland": "핀란드",
  "Austria": "오스트리아",
  "Ireland": "아일랜드",
  "New Zealand": "뉴질랜드",
  "South Africa": "남아프리카공화국",
  "Nigeria": "나이지리아",
  "Egypt, Arab Rep.": "이집트",
  "Iran, Islamic Rep.": "이란",
  "Iraq": "이라크",
  "Syrian Arab Republic": "시리아",
  "Jordan": "요르단",
  "Lebanon": "레바논",
  "Israel": "이스라엘",
  "Palestine": "팔레스타인",
  "Morocco": "모로코",
  "Algeria": "알제리",
  "Tunisia": "튀니지",
  "Ethiopia": "에티오피아",
  "Kenya": "케냐",
  "Ghana": "가나",
  "Colombia": "콜롬비아",
  "Argentina": "아르헨티나",
  "Chile": "칠레",
  "Peru": "페루",
  "Cuba": "쿠바",
  "Hong Kong SAR, China": "홍콩",
  "Taiwan, China": "대만",
  "Macao SAR, China": "마카오",
};

export function toKoreanCountryName(englishName: string): string {
  return COUNTRY_NAMES_KO[englishName] ?? englishName;
}
